import React, { useEffect, useState } from 'react'
import Input from '../../components/Input'
import Button from '../../components/Button'
import ImagesUpload from '../../components/ImagesUpload'
import { Form, useActionData, useNavigate } from '@remix-run/react'
import PasswordInput from '../../components/PasswordInput'
import { json, redirect } from '@remix-run/node'
// import { redirect } from 'next/dist/server/api-utils'
import { API_BASE_URL } from '../../utils/constants'
import LocationSelector from '../../components/LocationSelector'
import MultiselectLocation from '../../components/MultiselectLocation'
import Toast from '../../components/Toast'
import { getSession } from '../../sessionHandler.server'

export async function loader({ request }) {
    const session = await getSession(request);
    const user = session.get("user");

    if (user) {
        throw redirect("/admin/kitchen/cafe");
    }

    return null;
}

export async function action({ request }) {
    const contentType = request.headers.get("content-type");
    console.log("Received Content-Type:", contentType);

    if (!contentType || !contentType.includes("multipart/form-data")) {
        return json({ error: "Bad content-type", contentType }, { status: 400 });
    }

    const formData = await request.formData();

    const first_name = formData.get("first-name");
    const last_name = formData.get("last-name");
    const email = formData.get("email");
    const password = formData.get("password");
    const confirmPassword = formData.get("confirm-password");
    const selectLocations = formData.getAll("selected-locations[]").map(Number)
    selectLocations.sort()

    if (password !== confirmPassword) {
        return json({
            toast: {
                type: "error",
                message: error.message || "Password mismatch",
            }
        });
    }

    // 🔹 Step 1: Check if email already exists
    const checkEmailRes = await fetch(
        `${API_BASE_URL}/users?filter[email][_eq]=${encodeURIComponent(email)}`
    );
    const checkEmailJson = await checkEmailRes.json();

    if (checkEmailJson?.data?.length > 0) {
        return json({
            toast: {
                type: "error",
                message: "Email already registered",
            }
        });
    }

    // 🔹 Step 2: Handle multiple file uploads
    const images = formData.getAll("avatar"); // multiple files from ImagesUpload
    let uploadedImageIds = [];

    for (const image of images) {
        if (image && typeof image !== "string" && image.size > 0) {
            const uploadData = new FormData();
            uploadData.append("file", image, image.name);

            try {
                const uploadRes = await fetch(`${API_BASE_URL}/files`, {
                    method: "POST",
                    body: uploadData,
                });

                if (!uploadRes.ok) {
                    console.error("File upload failed:", await uploadRes.text());
                    continue;
                }

                const uploadJson = await uploadRes.json();
                if (uploadJson?.data?.id) uploadedImageIds.push(uploadJson.data.id); //store the id generated by endpoint in array
            } catch (error) {
                console.error("Error uploading avatar:", error);
            }
        }
    }

    // 🔹 Step 3: Create user (use the first uploaded image as avatar if any)
    const avatarId = uploadedImageIds.length > 0 ? uploadedImageIds[0] : null;

    const userRes = await fetch(`${API_BASE_URL}/users`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            first_name,
            last_name,
            email,
            password,
            avatar: avatarId,
            status: "active",
            allowed_locations: selectLocations,
        }),
    });

    if (!userRes.ok) {
        const err = await userRes.text();
        return json(
            {
                toast: {
                    type: "error",
                    message: err.message || "There is a problem in saving user",
                }
            }
        );
    }

    return json({
        toast: {
            type: "success",
            message: "User saved successfully"
        },
        redirectTo: "/login"
    });
}


function SignUp() {
    const [selectedLocations, setSelectedLocations] = useState([]);
    // Toast state
    const [toast, setToast] = useState(null);

    const navigate = useNavigate()

    const actionData = useActionData()
    useEffect(() => {
        if (actionData?.toast) {
            setToast(actionData.toast);

            // If redirect flag exists, wait 3 sec and redirect
            if (actionData.redirectTo) {
                setTimeout(() => {
                    navigate(actionData.redirectTo);
                }, 1000); // same as Toast auto-close time
            }
        }
    }, [actionData, navigate]);

    return (

        <div className="flex flex-col items-center justify-center min-h-screen gap-4 relative p-4">

            <div className="flex items-center justify-between w-full max-w-[400px]">
                SignUp
                <img src="/images/iss_logo.webp" width="50px" />
            </div>

            <Form method="post" encType="multipart/form-data" onSubmit={() => console.log("Form submitted")} className="flex flex-col gap-6 max-w-[400px] w-full">

                <Input type='name' name="first-name" required placeholder="Enter your first name" />

                <Input type='name' name="last-name" required placeholder="Enter your last name" />

                <Input type="email" required name="email" placeholder="Email" />

                <div>Upload your image</div>

                <ImagesUpload name="avatar" />

                <PasswordInput placeholder="Enter password" required name="password" />

                <PasswordInput placeholder="Confirm password" required name="confirm-password" />

                <MultiselectLocation
                    selectedLocations={selectedLocations}
                    setSelectedLocations={setSelectedLocations}
                    variant="black"
                />

                {selectedLocations.map(id => (
                    <input key={id} type="hidden" name="selected-locations[]" value={id} />
                ))}

                <Button type="submit">
                    Sign up
                </Button>

            </Form>
            {toast && (
                <Toast
                    message={toast.message}
                    type={toast.type}
                    onClose={() => setToast(null)}
                />
            )}
        </div>

    )
}

export default SignUp
